- README.md
this is based on common sense, someone should verify `dest` is correct (and `to` is wrong)
> corrected flag name (was 'to', now 'dest')

- src/portuguese/ExtendPor.gf
- src/portuguese/MakeStructuralPor.gf
- add PastPartAP, PastPartAgentAP
- add PassVPSlash, PassAgentVPSlash lins from ExtraRomance
- correct CompoundN
> (Por) Extend: add lins

- src/portuguese/ExtendPor.gf
- add ApposNP, ByVP, CompBareCN, ComplBareVS, GerundAdv, GerundNP, InOrderTo, PresPartAP, PurposeVP, WithoutVP
- added EmptyRelSlash which compiles fine but fails the linking phase, so not exported (@krangelov can you help me with this?)
> (ExtendPor) add lins

- src/abstract/Common.gf
> (Common) not all cats are linearized to SS

- .travis.yml
- Make.hs
- add ubuntu, mac, and windows builds
> (travis) refactor travis CI

- src/abstract/Construction.gf
- src/english/ConstructionEng.gf
- src/portuguese/ConstructionPor.gf
- src/portuguese/DiffPor.gf
- src/portuguese/ResPor.gf
- add Eng and Por lins
- fix documentation comments
> (Construction) add timeunitRange

- src/english/ParadigmsEng.gf
994e048 forgot to add paradigm to English (I hope that's the correct definition :)
> (Eng) fix missing paradigm invarA

- treebanks/ud-rgl-trees.txt
- rm duplicate trees
- correct parse trees
- always use Phr as startcat
> (UD treebank) fixes

- src/portuguese/IdiomPor.gf
- src/portuguese/LangPor.labels
- src/portuguese/LexiconPor.gf
- src/portuguese/StructuralPor.gf
- enough to parse (most of) the UD treebank
> (gf2ud) add minimal LangPor.labels

- src/portuguese/README
- src/romance/README
> (Romance, Por, #120) add READMEs

- src/english/LangEng.gf
- src/portuguese/MorphoPor.gf
- src/portuguese/ParadigmsPor.gf
- src/portuguese/TerminologyPor.gf
- add oper for compound nouns
- fix smartparadigm for adjectives
- fill Terminology to avoid warnings :sunglasses: 
(Eng) add pragma line to LangEng
> (Por) misc fixes

- src/portuguese/ConstructionPor.gf
- src/portuguese/DocumentationPorFunctor.gf
- src/portuguese/IdiomPor.gf
- src/portuguese/ParadigmsPor.gf
- add n_units_of_NP
- add n_unit_CN
- refactor adjective paradigm opers
- rm identity definitions in Idiom
> (Por) miscellaneous fixes

- src/portuguese/MorphoPor.gf
- src/portuguese/ParadigmsPor.gf
- src/portuguese/StructuralPor.gf
- src/portuguese/TextPor.gf
- use lin instead of `lock_*`
- also fix parenthesis that broke build
>  (Por) generalize acuteToVowel to diacriticToVowel

- languages.csv
- src/portuguese/LexiconPor.gf
- src/portuguese/ParadigmsPor.gf
- use gfdoc correctly
- use paradigms in Lexicon
- use lin instead of lock_* in Paradigms
- fix typo in languages.csv
> (Por) correct documentation generation from Paradigms

- src/portuguese/MorphoPor.gf
- src/portuguese/ParadigmsPor.gf
+ comment unnecessary cases
in noun paradigms
> (Por) correct examples

- src/abstract/Extend.gf
- src/common/ExtendFunctor.gf
- src/portuguese/ExtendPor.gf
- src/spanish/ExtendSpa.gf
(same as the one in `Extra{Por,Spa}`)
- with default UseComp lin
> (Extend,Por,Spa) add UseComp_estar

- src/portuguese/DiffPor.gf
- src/romance/DiffRomance.gf
- src/romance/QuestionRomance.gf
- src/spanish/DiffSpa.gf
- don't invert in QuestIAdv either
(Romance) allow for finer-grained choice of when to invert word order in questions
> (Por,Spa) don't invert word order in questions most of the time

- src/portuguese/ExtendPor.gf
> (Por) add GenRP to ExtendPor

- src/portuguese/DiffPor.gf
- wanted to switch P2 and P3, not have P1 become P3
> (Por) fix mkImperative

- src/portuguese/DiffPor.gf
- src/portuguese/LexiconPor.gf
- src/portuguese/ParadigmsPor.gf
- src/spanish/LexiconSpa.gf
- make it the default
- add paradigm to pick verb type (pick auxiliary verb or make it
reflexive)
(Por,Spa) fix lexicon entry
> (Por) add ter as optional auxiliary verb

- src/catalan/AllCat.gf
- src/catalan/ExtendCat.gf
- src/common/ParamX.gf
- src/english/QuestionEng.gf
- src/italian/AllIta.gf
- src/italian/ExtendIta.gf
- src/romance/ResRomance.gf
- using ExtendRomanceFunctor
- can't compile ExtendFre using ExtendRomanceFunctor though..
\+ whitespace changes
> (Cat,Ita) add stub implementations of Extend

- src/somali/CatSom.gf
- src/somali/LexiconSom.gf
- src/somali/NounSom.gf
- src/somali/NumeralSom.gf
- src/somali/ParamSom.gf
- src/somali/PhraseSom.gf
- src/somali/ResSom.gf
+ Other misc. fixes, like impersonal pronoun contractions.
> (Som) WIP: Numerals, bugfixes in gender agreement.

- src/abstract/Extend.gf
- src/english/ExtendEng.gf
> Add ProgrVPSlash

- src/english/ExtendEng.gf
It seems 2a697eebb2f73556d62d3d6d26f14f1276c25d61 broke #273
> (Eng) Fix ProgrVPSlash

- Setup.bat
- src/slovak/ResSlo.gf
- Ignore the changes to Setup.bat
> Corrections to ResSlo.gf, mostly pronouns and numerals.

- src/japanese/AdverbJpn.gf
- src/japanese/NounJpn.gf
- src/japanese/VerbJpn.gf
The field `prepositive` was emptied when AdvCN was applied. Also did some cleanup.
> Fix a bug in Jpn AdvCN

- src/russian/LexiconRus.gf
- src/russian/MorphoRus.gf
Only three verbs (see, hate, go) needed the "д", so they were redefined as irregulars, and a lot of verbs were fixed by making Second and SecondA synonymous.
NB: hasConj has some different use for SecondA, so it was not touched.
Also, fly_V has been fixed as it really belongs to the first conjugation.
When checking tests, it was noticed, that hunt, like, and fear are used in non-reflexive way while they are inherently reflexive, but fixing that is out of scope in this PR.
As can be seen from the diff below, see, hate, go continue to be conjugated as before (they are not in the diff).
```
* fly_V
** UseCl (TTAnt TPres ASimul) PPos (PredVP (ConjNP or_Conj (ConsNP (UsePron youSg_Pron) (BaseNP something_NP (UsePron she_Pron)))) (UseV ∅))
LangRus-NEW> что-то, она или ты летаешь
LangRus-OLD> …
```
> Deprecate SecondA conjugation, fix many words

- src/japanese/ResJpn.gf
1) Make `VerbalA` work for other verbs than いる
2) Only drop the last character of the attributive form, if it's の or な. Otherwise keep attributive intact even in the `adv` and `dropNaEnging` fields, e.g. in the case of `tired_VP = mkVP (mkA "疲れている" "疲れた") ;`
These changes are necessary for a particular application grammar I'm working on, so I will merge this immediately. But my changes in the code changes also some other forms, which are not needed in the application grammar.
@lizazim Could you check if the following forms are correct? I paste some examples of new vs. old behaviour. (The sentences are generated by gftest, so they are weird.)
```haskell
UseCl (TTAnt TPres ASimul) PPos (GenericCl (UseComp (CompAP (ConjAP or_Conj (BaseAP (PositA wet_A) (AdjOrd right_Ord))))))
LangJpn NEW> 誰か …
```
> Fixes in Jpn adjectives

- src/hungarian/NounMorphoHun.gf
- src/hungarian/ParadigmsHun.gf
- src/hungarian/ResHun.gf
- src/hungarian/StructuralHun.gf
Some more tweaks.
Tested with gftest + LexiconHun (revealed two errors before fix: computer_N and queen_N) and a 123-word list of multiwords from an application grammar.
> Hungarian: vowel harmony + handle multiwords

- src/finnish/CatFin.gf
- src/finnish/ConjunctionFin.gf
- src/finnish/ExtraFin.gf
- src/finnish/MarkupFin.gf
- src/finnish/PhraseFin.gf
- src/finnish/QuestionFin.gf
- src/finnish/ResFin.gf
- src/finnish/TerminologyFin.gf
- src/finnish/VerbFin.gf
Add oper that puts the fields of CN together + use it in the code.
> CN in Finnish

- Setup.sh
the Setup.hs already does the right thing, with `createDirectoryIfMissing`
> mkdir -p $GF_LIB_PATH if it doesn't already exist

- src/estonian/AdjectiveEst.gf
- src/estonian/AdverbEst.gf
- src/estonian/AllEst.gf
- src/estonian/AllEstAbs.gf
- src/estonian/CatEst.gf
- src/estonian/ConjunctionEst.gf
- src/estonian/ConstructionEst.gf
- src/estonian/DocumentationEst.gf
- src/estonian/DocumentationEstEng.gf
- src/estonian/DocumentationEstFunctor.gf
- src/estonian/ExtendEst.gf
- src/estonian/ExtraEst.gf
- src/estonian/ExtraEstAbs.gf
- src/estonian/GrammarEst.gf
- src/estonian/IdiomEst.gf
- src/estonian/LexiconEst.gf
- src/estonian/MakeStructuralEst.gf
- src/estonian/MorphoEst.gf
- src/estonian/NounEst.gf
- src/estonian/ParadigmsEst.gf
- src/estonian/PhraseEst.gf
- src/estonian/QuestionEst.gf
- src/estonian/RelativeEst.gf
- src/estonian/ResEst.gf
- src/estonian/SentenceEst.gf
- src/estonian/StructuralEst.gf
- src/estonian/SymbolEst.gf
- src/estonian/TerminologyEst.gf
- src/estonian/VerbEst.gf
- src/estonian/unittest/comitative.gftest
WIP. This is just the first batch of changes, mostly added a whole bunch of lins in Extend + couple of tweaks in other modules.
Plan is to restructure VP and possibly nominal categories too, to use stem-based inflection tables so we can fit more forms + hopefully make the grammar smaller.
> Improvements in Estonian

- src/estonian/AllEstAbs.gf
- src/estonian/ExtendEst.gf
- src/estonian/VerbEst.gf
* Fixed the verb form for PastPartAP, PastPartAgentAP
* Added AdvVPSlash and VPSlashPrep
* AllEstAbs uses Extend
> Minor fixes + new lins in Estonian

- src/german/NumeralGer.gf
Linearizations for millions (Millionen) and billions (Milliarden) added, with Sg "eine Million", "eine Milliarde".
Replaced "hundert" by "einhundert" for "one hundred" in pot2 and added "hundert" for "a hundred"  as pot21.
> (Ger) Added missing linearizations pot21 to pot5plus in NumeralGer
