.travis.yml
using dockerfile in https://github.com/odanoburu/docker-gf/blob/master/haskell-gf/Dockerfile
basically, this takes the standard haskell docker image, installs gf using the .deb file, and then runs the `Make.sh` and `Make.hs` scripts.
1. there seems to exist a missing file in the mongolian language, which is why I excluded it.
2. I've tested it again, and `Make.hs` will fail the build when there are errors, but `Make.sh` won't; apparently we have to change it to exit with non-zero codes when its calls to gf go awry.
3. two days ago I've helped someone build GF on their computer, and the haskell script failed, while the shell one worked fine. the same happens in docker, unless I build with shell script first. I suspect it is a problem in the script: running `GF_LIB_PATH=/home/rgl runghc …
=> use docker for ci

src/turkish/CatTur.gf, src/turkish/NounTur.gf
I have completed a good part of the linearizations in `NounTur.gf`. To be specific, this pull request contains linearizations for the following terms:
- `AdNum`,
- `AdjDAP`,
- `ApposCN`,
- `ComplN3`,
-  `CountNP`,
- `DetDAP`,
- `DetNP`,
- `ExtAdvNP`,
- `NumDigits`,
- `OrdNumeralSuperl,`
- `PPartNP`,
- `PartNP`,
- `PossNP`,
- `PredetNP,`
- `SentCN`,
- `RelCN`, and
- `RelNP`.
=> Complete some missing linearizations in NounTur

doc/AbsFunDoc.hs
change config filename in AbsFunDoc.hs to generate UDlabels in documentation. The new location (after the repositories were split) of the UD configs is gf-rgl/src/Lang.labels.
=> Fix to AbsFunDoc.hs

src/german/IrregGer.gf, src/german/IrregGerAbs.gf
Updated the spelling of irregular German verbs (the rules have changed, see [https://en.wikipedia.org/wiki/German_orthography_reform_of_1996](https://en.wikipedia.org/wiki/German_orthography_reform_of_1996)).
The old spellings are kept at the end of the file.
=> (Ger) fix old spellings of irregular verbs

src/catalan/LexiconCat.gf, src/catalan/ParadigmsCat.gf, src/french/ParadigmsFre.gf, src/italian/ParadigmsIta.gf, src/portuguese/ExtendPor.gf, src/portuguese/LexiconPor.gf, src/portuguese/ParadigmsPor.gf, src/romance/AdjectiveRomance.gf, src/romance/CatRomance.gf, src/romance/ConjunctionRomance.gf, src/romance/VerbRomance.gf, src/spanish/LexiconSpa.gf, src/spanish/ParadigmsSpa.gf
- so that one can force the use of a copula verb
- before this, a sentence like "he was ready when I saw him" would be
translated as "ele era pronto quando eu o via" in Portuguese,
instead of using the estar copula
=> (Romance) add copTyp to adjectives

src/portuguese/DiffPor.gf, src/romance/DiffRomance.gf, src/romance/ResRomance.gf, src/romance/SentenceRomance.gf, src/spanish/LangSpa.gf
for Portuguese it's best to
- pick imperfect tense when tense/anteriority is present anterior
- pick perfect tense when tense/anteriority is past simultaneous
this increases compilation times for Portuguese in 10 seconds though.
=> (Romance,Por) allow Romance Languages to choose different verb forms for the same tense/anteriority

src/portuguese/MorphoPor.gf
- handle 'ão' better (thanks @inariksit!)
- add more cases (for compounds with hyphen, acutes ending in 'l', etc
- concentrate smartness in mkNomReg (i.e., make smartGenNoun dumb)
=> (Por) improve smart paradigm for nouns

src/portuguese/DiffPor.gf
- in order to follow Romance more closely, we only avoid using the
auxiliary in (RPres,Anter), instead of swapping the perfect and
imperfect forms too
=> (Por) differ from Romance tense/anteriority in only one case

src/portuguese/DiffPor.gf, src/portuguese/ParadigmsPor.gf, src/romance/DiffRomance.gf
Portuguese actually has several verbs that can act as copulas,
although the main ones are ser and estar. this allows other types of
copulas to be added.
=> (Por) change copula type from bool to sum param

src/catalan/DiffCat.gf, src/portuguese/DiffPor.gf, src/portuguese/ExtraPor.gf, src/portuguese/LexiconPor.gf, src/spanish/DiffSpa.gf
- reflexive pronoun is before the verb in the negative, not after
- verb form is not the same as positive imperative, but the same as
present subjunctive
thanks to @inariksit for catching this bug!
(Por) handle politeness better
formal -> 2nd person singular (tu)
informal sg -> 3rd person singular (você, conjugated correctly)
informal pl -> 3rd person plural (vocês, conjugated correctly)
unlike Spa, Por uses 2nd person as polite form; the PorRG thus would
have no direct access to vós (second person plural), which is rather
rare (in Brazilian Por, at least). colloquial speech in Brazil
actually mangles both, using tu with você conjugation, etc; but this
out of scope for the RGL.
(Por) fix imperative
- should use hyphen to bind the reflexive pronoun
(Por) update lexicon given past changes …
=> (Cat,Por,Spa) Iberic imperative

src/catalan/DiffCat.gf, src/common/ExtendFunctor.gf, src/french/DiffFre.gf, src/italian/DiffIta.gf, src/portuguese/ConstructionPor.gf, src/portuguese/DiffPor.gf, src/portuguese/ExtendPor.gf, src/portuguese/IdiomPor.gf, src/romance/DiffRomance.gf, src/romance/ExtendRomanceFunctor.gf, src/spanish/DiffSpa.gf, src/spanish/ExtendSpa.gf
- couldn't get a functor on top of another working in GFSS2018, so now
we just copy the relevant definitions from ExtendFunctor and add the
Romance-specific ones
- add stare_V to DiffRomance (and essere_V for symmetry) so that we
can use it in ExtendRomance; using Latin verb name for fairness;
- add two missing lins to ExtendFunctor
+ related changes
=> (Romance,Por,Spa) refactor Extend{Por,Spa} into ExtendRomanceFunctor

src/french/MorphoFre.gf, src/french/ParadigmsFre.gf
It seems like the arguments got mixed up after recent updates to both mkA-paradigms and the mkAdj'-function in MorphoFre. I noticed it because i had some unittests set up with french feminine plural forms that started linearizing as masculine plurals. This change fixes it at least for mk4A and mk5A, not sure if there are other dependent functions using mkAdj' that may be affected.
=> French mixed up arguments

src/portuguese/DiffPor.gf, src/portuguese/LangPor.labels, src/portuguese/LexiconPor.gf, src/portuguese/StructuralPor.gf
for example
```
-- from the RGL treebank
l UttNP (PredetNP not_Predet everybody_NP)
not everybody
não todos -> nem todos
```
=> (Por) small fixes

src/portuguese/DiffPor.gf, src/portuguese/ExtendPor.gf, src/spanish/ExtendSpa.gf, treebanks/ud-rgl-trees.txt
* correct tree in ud treebank
- needs Extend's EmbedSSlash
* (Por) add EmbedSSlash
* (Por) change verb form for RPasse AAnter
the current linearization of RPasse Anter tense combination is not
grammatical Portuguese, while the auxiliar in the present + participle
past form is not available anywhere (it is grammatical Portuguese but
not as common as simple past, which gets the RPast ASimul
linearization)
=> (Por, UD) misc fixes

src/german/CatGer.gf, src/german/ConstructionGer.gf, src/german/DictVerbsGer.gf, src/german/ExtraGer.gf, src/german/IrregGer.gf, src/german/LexiconGer.gf, src/german/NounGer.gf, src/german/ParadigmsGer.gf, src/german/ResGer.gf, src/german/SentenceGer.gf, src/german/StructuralGer.gf, src/german/VerbGer.gf, tests/german/TestLang.gf, tests/german/TestLangEng.gf, tests/german/TestLangGer.gf, tests/german/TestLexiconEng.gf, tests/german/TestLexiconGer.gf, tests/german/TestLexiconGerAbs.gf, tests/german/examples.dub.out, tests/german/examples.eng.out, tests/german/examples.eng2ger.out, tests/german/examples.neg.out, tests/german/examples.pos.out, tests/german/examples.txt, tests/german/object-order.README, tests/german/object-order.gfs
In Ger, Pron.acc comes before Pron.dat|gen, while generally NP.dat comes before NP.acc. These are now
enforced (but not NP.acc before NP.gen), and that Refl < Pron < NP < neg < PP | AP | CN | Adv.
accdatV3 is changed (to c2=acc, c3=dat) to fit to Eng (c2=dir, c3=indir). Tests are under src/tests/german.
=> Pron ordering

src/german/ExtraGer.gf, src/german/ResGer.gf, src/german/SentenceGer.gf, src/german/VerbGer.gf, tests/german/vp-paradigm.README, tests/german/vp-paradigm.diff, tests/german/vp-paradigm.gfs, tests/german/vp-paradigm.out
The inf part of VPC is split into inf,inf2:Str to correct
hat ... wollen lesen         => hat ... lesen wollen
wird ... wollen haben lesen  => wird ... haben lesen wollen
(for: lesen wollen|gewollt haben)
Changed useVP and mkClause of ResGer and MkVPS of ExtraGer.
(ExtraGer.DisToCl needs to be adapted, but best by unification with mkClause.)
See also tests/german/vp-paradigm.*
=> (Ger) Correction of VP paradigm with modal verbs

src/russian/MorphoRus.gf
Please refer to the discussion in dev list: https://groups.google.com/d/msg/gf-dev/bZA37JAm5h0/skeo087kBgAJ 
- add_sya first case never works in Unicode world
- a couple of cases are useless unless they choose right constructor (perfective / imperfective)
=> Small fixes to Russian RG

src/russian/MorphoRus.gf
It turned out that `VIND GPl (VPresent P3)` is being used in participle creation to get verb form. The corrected code still returns non-existent verb forms, but at least does not break processing elsewhere.
=> Corrected mkVerbPerfective to not return nonExist

src/russian/LexiconRus.gf, src/russian/MorphoRus.gf
Fixes problem with a very important verb.
Also fixed become_VA conjugation, which caused some odd forms like "становдит"
Past tense of "мочь" are: "мог", "могла", "могло", "могли".
```
* can_VV
** UseCl (TTAnt TCond ASimul) PPos (PredVP (UsePron she_Pron) (ComplVV ∅ tired_VP))
LangRus-NEW> она могла бы быть уставшим
LangRus-OLD> она мога бы быть уставшим
** UseCl (TTAnt TCond ASimul) PPos (PredVP everybody_NP (ComplVV ∅ tired_VP))
LangRus-NEW> все могли бы быть уставшим
LangRus-OLD> все моги бы быть уставшим
** UseCl (TTAnt TCond ASimul) PPos (PredVP everything_NP (ComplVV ∅ tired_VP))
LangRus-NEW> всё могло бы быть уставшим
LangRus-OLD> всё мого бы быть уставшим
** UseCl (TTAnt TPast ASimul) PPos (PredVP (UsePron she_Pron) (ComplVV ∅ tired_VP))
LangRus-NEW> она могла быть уставшим …
```
=> Fix can (moch) in Russian RG

src/russian/MorphoRus.gf
I've noticed, that must_VV does not work properly:
1. Is always used Masc ("она должен быть уставшим" -> "она должна быть уставшим"
2. Words clung together ("быладолжна" --> "была должна")
I am not quite sure how adjective "должен" ended up being a verb (it's an adjective with only short form), but I enabled propagation of gender and it started to work.
While overall tests show more correct results, there is still room for improvement (as for example gender does not propagate to tired_VP in the tests, something_NP is Neuter, and some subtler cases ...)
```
* must_VV
** UseCl (TTAnt TCond ASimul) PPos (PredVP (UsePron she_Pron) (ComplVV ∅ tired_VP))
LangRus-NEW> она была должна бы быть уставшим
LangRus-OLD> она быладолжна бы быть уставшим
** UseCl (TTAnt TCond ASimul) PPos (PredVP …
```
=> Fix must (dolzhen) in Rus RG

src/russian/LexiconRus.gf, src/russian/MorphoRus.gf, src/russian/ParadigmsRus.gf
There is no such conjugation in Russian. It's the same as First.
Not sure how deprecation is being done in RGL, so no destructive changes (I'd removed that "Foreign" totally).
Lexicon tests show no changes.
=> Conjugation class Foreign is not needed, coincides with First

src/russian/ParadigmsRus.gf
The opers and comments in ParadigmsXxx need to follow a particular syntax in order to show in the RGL synopsis (https://www.grammaticalframework.org/lib/doc/synopsis/index.html#toc117). Also includes automatic whitespace removal.
=> (Rus) Fix syntax in ParadigmsRus to show in synopsis

unittest/unittest.py
while implementing a test case I stumbled upon syntax errors that (although being my own fault) were a bit cryptic to decipher, like not being able to have a blank line at the end of the file. these changes make the parser less strict, accepting minor deviations from the format like having multiple blank lines between test cases.
- accepts whitespace before comment starts
- accepts blank lines after last test case, or more than one of them
between test case
I've run tests with Hungarian and Portuguese (soon to be a PR), and it doesn't seem like I've changed the parser behavior in unintended ways, but please do review!
=> (unittest.py) more forgiving parser

doc/rgl-publications.txt, doc/status.txt
I updated the HTML versions manually, since it looks like they aren't generated from the txt files. Correct me if I'm wrong. 
* http://www.grammaticalframework.org/lib/doc/status.html
* http://www.grammaticalframework.org/lib/doc/rgl-publications.html
In the status document, I removed the field "in Git", because apart from Tswana, all languages were in Git. I also changed the column about (now deprecated) wide-coverage translation to indicate the WordNet status.
=> Update RGL status doc + publications

.github/workflows/build.yml, Setup.sh
Uses the Bash build script `Setup.sh` to avoid installing Haskell in the worker.
Eventually we should have regular RGL releases with these gfo packages attached for easy downloading.
=> Add workflow for building entire RGL

.travis.yml
Windows build hasn't work for some time now, and no test isn't worse than always failing test.
=> Comment out Windows build from Travis

src/english/CatEng.gf, src/english/ParadigmsEng.gf, src/english/RelativeEng.gf, src/english/StructuralEng.gf, src/english/unittest/relative.gftest, unittest/unittest.py
The functionalities added in #381 are in Extend.GenRP instead. (Almost—GenRP takes a CN, not NP, so it's impossible to say "John, whose every friend is right". But such a function is easy to add in applications, if anyone ever needed one.)
In addition, change unit tests to use AllEng.gf instead and GenRP function.
Change also the Python file to accept AllXxxAbs as an abstract syntax.
=> Revert changes in FunRP from #381

src/english/ExtendEng.gf, src/english/ExtraEng.gf, src/english/IdiomEng.gf, src/english/ResEng.gf
This PR changes the lincat of VP in the English resource grammar. 
I have tested the grammar in development with gftest to confirm that the linearisations haven't changed.
It reduces the fields in VP by two orders of magnitude, and makes the grammar better suited for morphological analysis. All verbs except auxiliaries only need 4 forms inside VP, and all other forms can be built in PredVP. The same for auxiliaries, but just more forms inside VP.
So I put two fields inside a VP, `auxForms : Aux` and `nonAuxForms : Str*4`, and add a parameter `isAux` that tells which field to use when building a Cl.
Why both fields?
* If we treat auxiliaries as normal verbs, we get "you don't be __" for "you aren't __", and that's obviously wrong.
* If we didn't care about morphological lexicon, we could …
=> (Eng) Fewer fields in VP

src/german/CatGer.gf, src/german/ConstructionGer.gf, src/german/DocumentationGerFunctor.gf, src/german/ExtendGer.gf, src/german/ExtraGer.gf, src/german/IdiomGer.gf, src/german/ParadigmsGer.gf, src/german/QuestionGer.gf, src/german/ResGer.gf, src/german/SentenceGer.gf, src/german/VerbGer.gf, src/malay/AllMayAbs.gf, tests/german/TestLang.gf, tests/german/TestLangEng.gf, tests/german/TestLangGer.gf, tests/german/TestLexiconGer.gf, tests/german/infinitives.lin.out, tests/german/vp-paradigm.gfs
- removed Control and treat control verbs with VPSlash.objCtrl:Bool
- combined VP.inf and VP.infExt to VP.inf with inplace/extracted parts
depending on Agr, to subj/obj-control reflexives in infinitival complements
- AllGer compiles from src in 250s (SlashV2VNP!), .gfo loads in 15s on x86_64
=> (Ger) reimplementation of infinitives to improve compilation

src/russian/InflectionRus.gf
While dealing with my own grammar I discovered, that йка-ending Russian nouns have wrong ending in plural genitive:
Crud> l Doc (ActorDoes3 ActorTask Copy3 (Every Message) (Nof (IDig D_9) Setting))
task copies every message to 9 settings .
задание копирует каждое сообщение в 9 настройек .
The й should not be there in "настройек".
After this fix:
Crud> l Doc (ActorDoes3 ActorTask Copy3 (Every Message) (Nof (IDig D_9) Setting))
task copies every message to 9 settings .
задание копирует каждое сообщение в 9 настроек .
which is correct.
=> Fix plgen of 3*a nouns, eg stroika

src/estonian/CatEst.gf, src/estonian/ConjunctionEst.gf, src/estonian/ConstructionEst.gf, src/estonian/DocumentationEstFunctor.gf, src/estonian/ExtendEst.gf, src/estonian/ExtraEst.gf, src/estonian/ExtraEstAbs.gf, src/estonian/IdiomEst.gf, src/estonian/NounEst.gf, src/estonian/NumeralEst.gf, src/estonian/ParadigmsEst.gf, src/estonian/QuestionEst.gf, src/estonian/RelativeEst.gf, src/estonian/ResEst.gf, src/estonian/SentenceEst.gf, src/estonian/TerminologyEst.gf, src/estonian/VerbEst.gf
Mostly just removing dead code and lock field warnings. The only nontrivial change is to the internal oper existClause, which so far has been used only from certain functions, and it dropped a bunch of fields from the argument, because those fields were empty anyway. I added those fields back to the output, with the idea that an application grammar might use that internal oper, and the argument may have any fields. (It was anyway bad behaviour in the first place to drop those fields.)
=> Minor fixes/cleanup in Estonian

src/finnish/ParadigmsFin.gf
Now featuring
- 3 explicit functions hidden from the API:
- mk2NsgGen, mk2NsgPar, mk2NsgIll
- Default 2-argument mkN also accepts singular genitive and plural nominative—best results still with plural partitive.
=> (Fin) New forms to 2-argument mkN opers in ParadigmsFin

src/finnish/MorphoFin.gf, src/finnish/ParadigmsFin.gf
A few more pattern matches in the alternative 2-argument paradigms, and allowing punctuation to follow an abbreviation.
=> Small fixes in Finnish noun paradigms

src/finnish/ParadigmsFin.gf
Another alternative 2-arg paradigm, for Sg Nom and Pl Gen.
Not provided via the API; instead, to be used directly in application via `mk2NplGen`. Only use this if pl genitive is the most informative form you have available.
=> (Fin) new 2-arg paradigm for N outside API

.github/workflows/test.yml
This should warn about build failures. 
Here's an example of a successful run: https://github.com/anka-213/gf-rgl/actions/runs/5867073985
And here's an example of a build failure: https://github.com/anka-213/gf-rgl/actions/runs/5867108591
=> Check in CI that building the RGL succeeds

src/german/AdjectiveGer.gf, src/german/AdverbGer.gf, src/german/CatGer.gf, src/german/ConjunctionGer.gf, src/german/ConstructionGer.gf, src/german/DocumentationGerFunctor.gf, src/german/ExtendGer.gf, src/german/ExtraGer.gf, src/german/ExtraGerAbs.gf, src/german/GrammarGer.gf, src/german/IdiomGer.gf, src/german/LexiconGer.gf, src/german/MakeStructuralGer.gf, src/german/MarkupGer.gf, src/german/MorphoGer.gf, src/german/NounGer.gf, src/german/ParadigmsGer.gf, src/german/PhraseGer.gf, src/german/QuestionGer.gf, src/german/RelativeGer.gf, src/german/ResGer.gf, src/german/SentenceGer.gf, src/german/StructuralGer.gf, src/german/SymbolGer.gf, src/german/VerbGer.gf
(Ger) Shrink Agr = Ag Gender Number Person from 3*2*3 = 18 values to 9, including polite plural 
Agr = AgSgP1 | AgSgP2 | AgSgP3 Gender | AgSgP3Gen | AgPl Person | AgPlPol ;
Compiles AllGer from src in 145sec with 15M VerbGer.gfo vs. 380sec with 17M VerbGer.gfo
=> Smaller Agr for Ger

src/german/CatGer.gf, src/german/NumeralGer.gf
Digits d- in {0,...,9}+ get endings as follows
NOrd (AMod gennum case)
1.   Nom: d-ter,d-te,d-tes,         for 0 and d ending in 1 =< d =< 19,
2.   Nom: d-ster, d-ste, d-stes, else.
NOrd APred: 
1. am 0ten, ..., am 19ten, 
2. am 20sten,...,am 99sten, am 100sten, 
3. am 101ten,...,am 119ten, 
4. am 120sten,...,am 199sten, am 200sten
etc.
=> (Ger) ordinal endings of Digits fixed

src/german/AdjectiveGer.gf, src/german/AllGer.gf, src/german/AllGerAbs.gf, src/german/CatGer.gf, src/german/ConstructionGer.gf, src/german/ExtendGer.gf, src/german/ExtraGer.gf, src/german/ExtraGerAbs.gf, src/german/MakeStructuralGer.gf, src/german/MorphoGer.gf, src/german/NamesGer.gf, src/german/NounGer.gf, src/german/NumeralGer.gf, src/german/ParadigmsGer.gf, src/german/PhraseGer.gf, src/german/QuestionGer.gf, src/german/ResGer.gf, src/german/StructuralGer.gf, src/german/SymbolGer.gf, src/german/TerminologyGer.gf, src/german/VerbGer.gf
1. Changed some types .. => Number => Gender => .. to .. => GenNum => to get rid of gender in plural 
2. Reduced the paradigm of Quant and reimplemented DetQuant and DetQuantOrd to handle the dependence on num.isNum there (and add special treatment of num = cardinal 1)
3. Corrected the sp-paradigm and adjective inflection type of several determiners in Structural
4. Increased Extend and use in in AllGer instead of Extra
Some inflection of small cardinals needs to be implemented, e.g. "wir erklaeren euch drei-en die Loesung zwei-er Probleme". So far, Card.s : AForm => Str is used only for cardinal 1, "der ein-e", "mein ein-er" etc.
=> (Ger) Determiners and DetQuant, DetQuantOrd improved; gender in plural removed; Extend extended
